name: Symfony CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: hobbini_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    steps:
      - uses: actions/checkout@v4

      # PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      # Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      # Composer
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      # ENV for test
      - name: Set environment variables
        run: |
          echo "APP_ENV=test" >> $GITHUB_ENV
          echo "DATABASE_URL=mysql://root:root@127.0.0.1:3306/hobbini_test?serverVersion=8.0&charset=utf8mb4" >> $GITHUB_ENV

      # Wait MySQL ready (IMPORTANT)
      - name: Wait for MySQL
        run: |
          for i in {1..40}; do
            mysqladmin ping -h 127.0.0.1 -uroot -proot --silent && echo "MySQL ready" && exit 0
            echo "Waiting MySQL..."
            sleep 2
          done
          echo "MySQL not ready" && exit 1

      # DB schema
      - name: Create database schema
        run: php bin/console doctrine:schema:create --env=test -n

      # Run tests
      - name: Run PHPUnit
        run: php bin/phpunit